project_id = "fhdylzpmzvumzmcevbrz"

[auth]
site_url = "http://localhost:5173"

[auth.email]
enable_signup = true
double_confirm_changes = true

[functions]
[functions.send-otp]
verify_jwt = false
import_map = "./functions/send-otp/deno.json"
